subdir = src/backend/access/merkle
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	merkle.o \
	merklebuild.o \
	merkleinsert.o \
	merkleverify.o \
	merkleutil.o

include $(top_srcdir)/src/backend/common.mk
